name: Node.js CI

on:
    push:
        branches: [ dev ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-node@v2
                with:
                  node-version: '16'
                  cache: 'npm'
            
            -   name: Build
                run: |
                    npm ci --legacy-peer-deps
                    npm run build
                    npm run export
                    touch out/.nojekyll
            
            -   name: Deploy
                # configure an external GitHub Pages deploy workflow here
                # https://github.com/JamesIves/github-pages-deploy-action
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    branch: gh-pages
                    folder: out
